### ISSUE TITLE
pod创建失败 镜像拉不下来

### ISSUE THREAD

**Issue by CrushCCD** [liuxuzxx/csi-s3#11]
![image](https://github.com/user-attachments/assets/ddb08f06-8e13-4c71-8ed0-a399a73c921f)

**Comment by liuxuzxx** [comment]
这个是我本地的镜像仓库地址，换一个

**Comment by liuxuzxx** [comment]
修改下csi-s3下面的values.yaml文件的如下信息:

```yaml
global:
  image: liuxuzxx/csi-s3
  tag: v1.4.0

minio:
  url: 10.20.121.130:9000  #换成自己的minio的地址
  accessKey: admin #换成自己minio的用户名
  accessSecret: minioadmin #换成自己Minio的密码
  bucket: k8s-dev-sc-130 #换成自己的minio创建的bucket
```
